#!/usr/bin/env python3
"""Deterministic replay gate for the DISAGREEMENTS baseline (P1, item 0).

DISAGREEMENTS needs each policy's action values on the *other* policies' states.
The stored `evaluation/steps.csv` carries only the acting policy's Q vector and
no observations, so the states have to be regenerated by replaying the stored
rollouts. Everything the baseline reports is derived from that replay, so the
replay itself has to be verified before any of it is trusted.

This script replays each evaluation rollout with the recorded model and checks,
step for step, that the replayed action name, ego lane, ego speed, and ego
position match the stored row. A single mismatch fails the gate for that
episode: it means the environment reconstruction diverged from the run that
produced the stored table, and no cross-policy quantity computed on top of it
would be meaningful.

While the leader's trajectory is being replayed it also queries the other two
policies on the same observation, which is exactly the information
DISAGREEMENTS consumes. Only the *count* of action disagreements is reported
here. Where those disagreements fall relative to the onset, and what verdict
they would support, are separate diagnostics governed by the still-draft
`experiments/summary_comparison/preregistration_v2.md`; no human-study scoring
is authorised before that protocol is frozen.

Run from the repository root:

    PYTHONPATH=src python3 scripts/p1_replay_check.py \
        --run-dir outputs/multilane_twolane_open_fixed_100k_seed4100 --arm B

Use `--max-exposures` for a quick check before committing to the full grid.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator, Mapping, Sequence

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from highway_transition_timing.constants import AGENTS  # noqa: E402
from highway_transition_timing.highway_adapter import (  # noqa: E402
    action_name_from_env,
    configure_headless_runtime,
    dqn_class_for_variant,
    extract_diagnostics,
    predict_action_and_scores,
    require_highway_deps,
)

#: Replay is deterministic, so the replayed floats should reproduce the stored
#: ones exactly. The tolerance only absorbs the 6-decimal rounding applied by
#: `step_row_from_diagnostics` when the table was written.
POSITION_TOLERANCE = 1e-5
SPEED_TOLERANCE = 1e-5


@dataclass(frozen=True)
class Arm:
    key: str
    label: str
    experiment: str
    apply_scene: str


ARMS = {
    "A": Arm(
        "A",
        "single lane",
        "single_lane_slow_front",
        "apply_single_lane_scene",
    ),
    "B": Arm(
        "B",
        "two lanes, open target lane",
        "multilane_open_lane_change",
        "apply_open_lane_scene",
    ),
    "C": Arm(
        "C",
        "two lanes, occupied target lane",
        "multilane_open_lane_change",
        "apply_open_lane_scene",
    ),
}


def load_experiment_module(experiment: str):
    """Import an experiment's `run.py` the way its own scripts do."""

    path = REPO_ROOT / "experiments" / experiment / "run.py"
    spec = importlib.util.spec_from_file_location(f"{experiment}_run", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load experiment module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def parse_bool(value: str | None, default: bool) -> bool:
    if value is None or value == "":
        return default
    return value.strip().lower() in {"1", "true", "yes"}


def optional_float(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    return float(value)


def training_run_row(run_dir: Path) -> dict[str, str]:
    path = run_dir / "training_runs.csv"
    if not path.exists():
        raise SystemExit(f"Missing {path}; cannot reconstruct the run config.")
    with path.open(newline="") as handle:
        return dict(next(csv.DictReader(handle)))


def config_for_arm(module, arm: Arm, run_dir: Path):
    """Rebuild the ExperimentConfig that produced the stored rollouts.

    Any field that reaches the environment has to come from the recorded run,
    not from a default. A silently wrong field would change the dynamics and
    the replay would diverge, which is what the verification below detects.
    """

    row = training_run_row(run_dir)
    common = {
        "evaluation_duration": int(
            float(row.get("evaluation_duration_seconds") or 120)
        ),
        "seed": int(row.get("seed", 0)),
        "policy_frequency": int(float(row.get("policy_frequency_hz") or 5)),
        "observation_normalize": parse_bool(row.get("observation_normalize"), True),
        "observation_absolute": parse_bool(row.get("observation_absolute"), False),
        "dqn_variant": row.get("dqn_variant") or "double-dqn",
    }

    if arm.key == "A":
        # The single-lane run records the shared penalties under
        # `configured_common_*`; `reward_*` there is the per-agent weight.
        target_speeds = row.get("target_speeds_mps") or ""
        extra: dict[str, Any] = {
            "slow_down_penalty": float(
                row.get("configured_common_slow_down_penalty") or 0.0
            ),
            "collision_risk_penalty": float(
                row.get("configured_common_collision_risk_penalty") or 3.0
            ),
            "collision_penalty": optional_float(
                row.get("configured_common_collision_penalty")
            ),
        }
        if target_speeds:
            # target_speeds reaches DiscreteMetaAction, so it changes the
            # dynamics rather than only the bookkeeping.
            extra["target_speeds"] = tuple(
                float(value) for value in json.loads(target_speeds)
            )
        return module.ExperimentConfig(**common, **extra)

    return module.ExperimentConfig(
        **common,
        lanes_count=int(row.get("lanes_count", 2)),
        ego_lane=int(row.get("ego_lane", 1)),
        target_lane_vehicle=parse_bool(row.get("target_lane_vehicle"), False),
        target_lane_speed=float(
            row.get("target_lane_speed") or module.TARGET_LANE_SPEED
        ),
        slow_down_penalty=float(row.get("reward_slow_down_penalty") or 0.2),
        lane_change_penalty=float(row.get("reward_lane_change_penalty") or 0.2),
        collision_risk_penalty=float(
            row.get("reward_collision_risk_penalty") or 3.0
        ),
        collision_penalty=optional_float(row.get("reward_common_collision_penalty")),
    )


def stored_steps(run_dir: Path) -> dict[tuple[str, int], dict[str, str]]:
    """Index the stored evaluation table by (episode_id, t)."""

    path = run_dir / "evaluation" / "steps.csv"
    if not path.exists():
        raise SystemExit(f"Missing {path}; nothing to verify the replay against.")
    rows: dict[tuple[str, int], dict[str, str]] = {}
    with path.open(newline="") as handle:
        for row in csv.DictReader(handle):
            rows[(row["episode_id"], int(row["t"]))] = row
    return rows


def stored_position(row: Mapping[str, str]) -> tuple[float, float]:
    value = json.loads(row["ego_position"])
    return float(value[0]), float(value[1])


def compare_step(
    stored: Mapping[str, str],
    action_name: str,
    diagnostics: Mapping[str, Any],
) -> list[str]:
    """Return the field names that disagree with the stored row."""

    mismatches: list[str] = []
    if stored["action"] != action_name:
        mismatches.append("action")
    if int(stored["ego_lane"]) != int(diagnostics["ego_lane"]):
        mismatches.append("ego_lane")
    if abs(float(stored["ego_speed"]) - float(diagnostics["ego_speed"])) > SPEED_TOLERANCE:
        mismatches.append("ego_speed")
    stored_x, stored_y = stored_position(stored)
    replay_x, replay_y = (float(v) for v in diagnostics["ego_position"])
    if (
        abs(stored_x - replay_x) > POSITION_TOLERANCE
        or abs(stored_y - replay_y) > POSITION_TOLERANCE
    ):
        mismatches.append("ego_position")
    return mismatches


def replay_episode(
    module,
    arm: Arm,
    config,
    models: Mapping[str, Any],
    leader: str,
    spec,
    stored: Mapping[tuple[str, int], Mapping[str, str]],
) -> dict[str, Any]:
    """Replay one leader rollout, verifying it and counting disagreements."""

    apply_scene = getattr(module, arm.apply_scene)
    followers = [agent for agent in models if agent != leader]
    episode_id = f"{leader}_{spec.exposure_id}_r0"

    env = module.make_env(leader, config, training=False)
    try:
        env.reset(seed=spec.exposure_seed)
        obs = apply_scene(env, spec)

        steps = 0
        first_mismatch_t: int | str = ""
        first_mismatch_fields = ""
        missing_rows = 0
        mismatched_steps = 0
        disagreements = {agent: 0 for agent in followers}

        done = False
        t = 0
        while not done and t < config.evaluation_max_policy_steps:
            action, _q_values = predict_action_and_scores(
                models[leader], obs, deterministic=True
            )
            action_name = action_name_from_env(env, int(action))

            # The other policies are queried on the leader's observation, which
            # is the state distribution DISAGREEMENTS actually searches.
            for agent in followers:
                follower_action, _ = predict_action_and_scores(
                    models[agent], obs, deterministic=True
                )
                if int(follower_action) != int(action):
                    disagreements[agent] += 1

            diagnostics = extract_diagnostics(env)
            stored_row = stored.get((episode_id, t))
            if stored_row is None:
                missing_rows += 1
            else:
                mismatches = compare_step(stored_row, action_name, diagnostics)
                if mismatches:
                    mismatched_steps += 1
                    if first_mismatch_t == "":
                        first_mismatch_t = t
                        first_mismatch_fields = "|".join(mismatches)

            obs, _reward, terminated, truncated, _info = env.step(int(action))
            steps += 1
            t += 1
            done = bool(terminated or truncated) or t >= config.evaluation_max_policy_steps
    finally:
        env.close()

    stored_length = sum(1 for key in stored if key[0] == episode_id)
    record = {
        "arm": arm.key,
        "leader": leader,
        "exposure_id": spec.exposure_id,
        "episode_id": episode_id,
        "replayed_steps": steps,
        "stored_steps": stored_length,
        "length_match": steps == stored_length,
        "missing_stored_rows": missing_rows,
        "mismatched_steps": mismatched_steps,
        "first_mismatch_t": first_mismatch_t,
        "first_mismatch_fields": first_mismatch_fields,
        "verified": (
            first_mismatch_t == ""
            and missing_rows == 0
            and steps == stored_length
        ),
    }
    for agent in AGENTS:
        record[f"disagreements_vs_{agent}"] = disagreements.get(agent, "")
    return record


def iter_specs(module, config, num_exposures: int, max_exposures: int | None):
    specs = module.make_eval_specs(num_exposures, config)
    if max_exposures is not None:
        specs = specs[:max_exposures]
    return specs


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, help="Completed training run.")
    parser.add_argument("--arm", required=True, choices=sorted(ARMS))
    parser.add_argument("--num-exposures", type=int, default=36)
    parser.add_argument(
        "--max-exposures",
        type=int,
        default=None,
        help="Replay only the first N exposures, for a quick check.",
    )
    parser.add_argument(
        "--agents",
        nargs="+",
        default=list(AGENTS),
        help="Agent conditions to replay as leader.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output CSV (default: outputs/summary_comparison/p1_replay_check/).",
    )
    return parser


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def print_report(arm: Arm, rows: Sequence[Mapping[str, Any]]) -> bool:
    verified = sum(1 for row in rows if row["verified"])
    print(f"\narm {arm.key} ({arm.label}): {verified}/{len(rows)} episodes verified")
    failures = [row for row in rows if not row["verified"]]
    if failures:
        print(
            f"{'episode':<24}{'steps':>7}{'stored':>8}{'bad steps':>10}"
            f"{'first bad t':>12}  fields"
        )
        for row in failures[:20]:
            print(
                f"{row['episode_id']:<24}{row['replayed_steps']:>7}"
                f"{row['stored_steps']:>8}{row['mismatched_steps']:>10}"
                f"{str(row['first_mismatch_t']):>12}  "
                f"{row['first_mismatch_fields']}"
            )
        if len(failures) > 20:
            print(f"... and {len(failures) - 20} more")
        return False

    print("\ndisagreement counts on the leader's states (structural only):")
    print(f"{'leader':<8}{'vs':<8}{'total':>8}{'mean/episode':>14}")
    for leader in sorted({row["leader"] for row in rows}):
        leader_rows = [row for row in rows if row["leader"] == leader]
        for agent in AGENTS:
            counts = [
                row[f"disagreements_vs_{agent}"]
                for row in leader_rows
                if row[f"disagreements_vs_{agent}"] != ""
            ]
            if not counts:
                continue
            print(
                f"{leader:<8}{agent:<8}{sum(counts):>8}"
                f"{sum(counts) / len(counts):>14.1f}"
            )
    return True


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    arm = ARMS[args.arm]
    run_dir = Path(args.run_dir)

    require_highway_deps(include_training=True)
    configure_headless_runtime()

    module = load_experiment_module(arm.experiment)
    config = config_for_arm(module, arm, run_dir)
    dqn_class = dqn_class_for_variant(config.dqn_variant)
    models = {
        agent: dqn_class.load(run_dir / "models" / f"{agent}_main.zip")
        for agent in args.agents
    }

    stored = stored_steps(run_dir)
    specs = iter_specs(module, config, args.num_exposures, args.max_exposures)

    rows: list[dict[str, Any]] = []
    for spec in specs:
        for leader in args.agents:
            rows.append(
                replay_episode(module, arm, config, models, leader, spec, stored)
            )

    out = args.out or (
        REPO_ROOT
        / "outputs"
        / "summary_comparison"
        / "p1_replay_check"
        / f"{run_dir.name}_replay_check.csv"
    )
    write_csv(out, rows)
    ok = print_report(arm, rows)
    print(f"\nwrote {out}")
    if not ok:
        print("\nGATE FAILED: the replay does not reproduce the stored rollouts.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
